const KEY='budgetquest-commercial-v1';
const defaultState={settings:{householdName:'Mein Haushalt',monthlyIncome:0,monthlySaving:0,currency:'CHF'},budgets:[{id:crypto.randomUUID(),name:'Lebensmittel',limit:800},{id:crypto.randomUUID(),name:'Freizeit',limit:300}],transactions:[],goals:[]};
let state=load();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF'}).format(Number(n)||0);
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function monthTx(){const m=new Date().toISOString().slice(0,7);return state.transactions.filter(t=>t.date?.startsWith(m))}
function renderDashboard(){const tx=monthTx();const income=Number(state.settings.monthlyIncome)+tx.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0);const expense=tx.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);const available=income-expense-Number(state.settings.monthlySaving||0);$('#availableHero').textContent=money(available);$('#incomeMetric').textContent=money(income);$('#expenseMetric').textContent=money(expense);$('#savingRate').textContent=income?Math.max(0,Math.round((income-expense)/income*100))+' %':'0 %';$('#monthSummary').textContent=tx.length?`${tx.length} Buchungen im aktuellen Monat`:'Noch keine Buchungen';const rows=state.budgets.map(b=>{const spent=tx.filter(t=>t.type==='expense'&&t.category===b.name).reduce((s,t)=>s+t.amount,0);const pct=Math.min(100,b.limit?spent/b.limit*100:0);return `<div class="budget-row"><div><b>${esc(b.name)}</b><div class="progress"><span style="width:${pct}%"></span></div><small class="muted">${money(spent)} von ${money(b.limit)}</small></div><strong class="${spent>b.limit?'negative':''}">${Math.round(pct)} %</strong></div>`}).join('');$('#budgetOverview').innerHTML=rows||'<p class="muted">Noch keine Budgets.</p>';const over=state.budgets.filter(b=>tx.filter(t=>t.type==='expense'&&t.category===b.name).reduce((s,t)=>s+t.amount,0)>b.limit);$('#coach').innerHTML=over.length?`<p class="negative">${over.length} Budget${over.length>1?'s':''} überschritten. Prüfe besonders ${over.map(x=>esc(x.name)).join(', ')}.</p>`:`<p class="positive">Du liegst aktuell in allen Kategorien innerhalb des Budgets.</p>`}
function renderBudgets(){const tx=monthTx();$('#budgetCards').innerHTML=state.budgets.map(b=>{const spent=tx.filter(t=>t.type==='expense'&&t.category===b.name).reduce((s,t)=>s+t.amount,0);return `<div class="budget-row"><div><b>${esc(b.name)}</b><div class="muted">Verbraucht ${money(spent)} · Limit ${money(b.limit)}</div></div><button class="danger" onclick="deleteBudget('${b.id}')">Löschen</button></div>`}).join('')||'<p class="muted">Noch keine Budgets.</p>'}
function renderTransactions(){const q=$('#searchInput')?.value?.toLowerCase()||'';const list=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).filter(t=>(t.title+' '+t.category).toLowerCase().includes(q));$('#transactionList').innerHTML=list.map(t=>`<div class="tx-row"><div><b>${esc(t.title)}</b><div class="muted">${t.date} · ${esc(t.category||'Ohne Kategorie')}</div></div><div><strong class="${t.type==='income'?'positive':'negative'}">${t.type==='income'?'+':'−'} ${money(t.amount)}</strong><br><button class="ghost" onclick="deleteTx('${t.id}')">Entfernen</button></div></div>`).join('')||'<p class="muted">Keine Buchungen gefunden.</p>'}
function renderGoals(){const icons={home:'🏡',saving:'💰',future:'🔭',sport:'🏃',other:'⭐'};$('#goalCards').innerHTML=state.goals.map(g=>{const pct=Math.min(100,g.target?g.saved/g.target*100:0);return `<article class="goal-card"><div class="head"><span style="font-size:2rem">${icons[g.type]||'⭐'}</span><button class="danger" onclick="deleteGoal('${g.id}')">×</button></div><h3>${esc(g.name)}</h3><div class="progress"><span style="width:${pct}%"></span></div><b>${money(g.saved)} / ${money(g.target)}</b><p class="muted">${Math.round(pct)} % erreicht${g.date?' · Ziel '+g.date:''}</p><button class="primary" onclick="addGoalSaving('${g.id}')">Einzahlung erfassen</button></article>`}).join('')||'<article class="card"><p>Noch kein Ziel erstellt. Eigenheim ist nur eine mögliche Zielart – du kannst auch Spar-, Zukunfts-, Sport- oder eigene Ziele anlegen.</p></article>'}
function renderSettings(){$('#householdName').value=state.settings.householdName;$('#monthlyIncome').value=state.settings.monthlyIncome;$('#monthlySaving').value=state.settings.monthlySaving;document.title=`${state.settings.householdName} · BudgetQuest`}
function renderCategories(){const opts=state.budgets.map(b=>`<option>${esc(b.name)}</option>`).join('')+'<option>Sonstiges</option>';$('#txCategory').innerHTML=opts}
function calculateHome(){const eq=+$ ('#homeEquity').value||0,inc=+$ ('#homeIncome').value||0,share=(+$ ('#homeShare').value||20)/100,aff=(+$ ('#homeAfford').value||33)/100,interest=(+$ ('#homeInterest').value||5)/100,maint=(+$ ('#homeMaintenance').value||1)/100;const eqLimit=share?eq/share:0;const annualRate=interest+maint+0.01;const affLimit=annualRate?inc*aff/annualRate:0;$('#equityLimit').textContent=money(eqLimit);$('#affordLimit').textContent=money(affLimit);$('#homeResult').textContent=money(Math.min(eqLimit,affLimit))}
function renderAll(){renderDashboard();renderBudgets();renderTransactions();renderGoals();renderSettings();renderCategories();calculateHome()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.deleteBudget=id=>{state.budgets=state.budgets.filter(x=>x.id!==id);save()};window.deleteTx=id=>{state.transactions=state.transactions.filter(x=>x.id!==id);save()};window.deleteGoal=id=>{state.goals=state.goals.filter(x=>x.id!==id);save()};window.addGoalSaving=id=>{const g=state.goals.find(x=>x.id===id);const val=Number(prompt('Einzahlung in CHF:'));if(g&&val>0){g.saved+=val;save();toast('Ziel aktualisiert')}};
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.target).classList.add('active');scrollTo(0,0)});
$$('[data-open]').forEach(b=>b.onclick=()=>$('#'+b.dataset.open).showModal());
$('#transactionForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;state.transactions.push({id:crypto.randomUUID(),type:$('#txType').value,title:$('#txTitle').value.trim(),amount:+$('#txAmount').value,date:$('#txDate').value,category:$('#txCategory').value});e.target.reset();$('#txDate').value=new Date().toISOString().slice(0,10);save();toast('Buchung gespeichert')});
$('#budgetForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;state.budgets.push({id:crypto.randomUUID(),name:$('#budgetName').value.trim(),limit:+$('#budgetLimit').value});e.target.reset();save();toast('Budget hinzugefügt')});
$('#goalForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;state.goals.push({id:crypto.randomUUID(),type:$('#goalType').value,name:$('#goalName').value.trim(),target:+$('#goalTarget').value,saved:+$('#goalSaved').value||0,date:$('#goalDate').value});e.target.reset();save();toast('Ziel erstellt')});
$('#saveSettings').onclick=()=>{state.settings.householdName=$('#householdName').value.trim()||'Mein Haushalt';state.settings.monthlyIncome=+$('#monthlyIncome').value||0;state.settings.monthlySaving=+$('#monthlySaving').value||0;save();toast('Einstellungen gespeichert')};
$('#searchInput').oninput=renderTransactions;$$('#home input').forEach(i=>i.oninput=calculateHome);$('#privacyBtn').onclick=()=>toast('Keine Finanzdaten werden übertragen');
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='budgetquest-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.settings||!Array.isArray(data.transactions))throw Error();state=data;save();toast('Backup importiert')}catch{alert('Ungültige BudgetQuest-Datei.')}};
$('#resetBtn').onclick=()=>{if(confirm('Alle lokalen BudgetQuest-Daten unwiderruflich löschen?')){localStorage.removeItem(KEY);state=structuredClone(defaultState);save();toast('Lokale Daten gelöscht')}};
$('#txDate').value=new Date().toISOString().slice(0,10);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
renderAll();